version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:./nginx.conf
    depends_on:
      - service1
      - service2
  service1:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./service1:/usr/share/nginx/html
  service2:
    image: node:14.10
    ports:
      - "3000:3000"
    volumes:
      - ./service2:/app
    command: npm run dev
    working_dir: /app
